### ISSUE TITLE
Duplicated files/folders

### ISSUE THREAD

**Issue by TehPsychedelic** [zkitX/AMS-CheatDB#2]
Hi,

I imagine you're on a *nix system because these folders or files are duplicated with different case
`
  'atmosphere/titles/010057D006492000/cheats/0d8a6a8804a6654c.txt'
  'atmosphere/titles/010057d006492000/cheats/0d8a6a8804a6654c.txt'
  'atmosphere/titles/010057D006492000/cheats/72fd3930fac64f21.txt'
  'atmosphere/titles/010057d006492000/cheats/72fd3930fac64f21.txt'
  'atmosphere/titles/0100B0C0086B0000/cheats/047fdd0c5af5f1c5.txt'
  'atmosphere/titles/0100b0c0086b0000/cheats/047fdd0c5af5f1c5.txt'
  'atmosphere/titles/0100B0C0086B0000/cheats/3469a1b2e0fea93c.txt'
  'atmosphere/titles/0100b0c0086b0000/cheats/3469a1b2e0fea93c.txt'
  'atmosphere/titles/0100D1B006744000/cheats/29E1A37D84227147.txt'
  'atmosphere/titles/0100d1b006744000/cheats/29e1a37d84227147.txt'
  'atmosphere/titles/0100DC300AC78000/cheats/2A979C3FDF717642.txt'
  'atmosphere/titles/0100DC300AC78000/cheats/2a979c3fdf717642.txt'
`

**Comment by zkitX** [comment]
Fixed
